name: DB Migrate (Prisma)

on:
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Normalize DATABASE_URL (add sslmode=require)
        id: dburl
        shell: bash
        run: |
          if [[ -z "${DATABASE_URL}" ]]; then
            echo "DATABASE_URL secret is empty or not accessible." >&2
            exit 1
          fi
          URL="${DATABASE_URL}"
          # Append sslmode=require if not already present
          if [[ "${URL}" == *"sslmode="* ]]; then
            echo "value=${URL}" >> "$GITHUB_OUTPUT"
          else
            if [[ "${URL}" == *\?* ]]; then
              URL="${URL}&sslmode=require"
            else
              URL="${URL}?sslmode=require"
            fi
            echo "value=${URL}" >> "$GITHUB_OUTPUT"
          fi

      - name: Quick TCP connectivity check with retries
        shell: bash
        env:
          URL: ${{ steps.dburl.outputs.value }}
        run: |
          HOST=$(node -e "const u=new URL(process.env.URL);console.log(u.hostname)")
          PORT=$(node -e "const u=new URL(process.env.URL);console.log(u.port||'5432')")
          echo "Checking connectivity to $HOST:$PORT ..."
          for i in {1..6}; do
            if nc -z -w 5 "$HOST" "$PORT"; then
              echo "Port open."
              exit 0
            fi
            echo "Attempt $i failed; retrying in 5s..."
            sleep 5
          done
          echo "Unable to reach $HOST:$PORT after retries." >&2
          exit 1

      - name: Install deps (fallback to npm if pnpm not present)
        shell: bash
        run: |
          corepack enable || true
          (pnpm install --frozen-lockfile) || npm ci

      - name: Prisma migrate deploy
        env:
          DATABASE_URL: ${{ steps.dburl.outputs.value }}
        run: npx --yes prisma@6.2.1 migrate deploy
