name: DB Migrate (Prisma)
on:
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npx --yes prisma@6.2.1 migrate deploy
